# Generated by Django 5.0.10 on 2024-12-23 04:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fb_pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("user_id", models.CharField(max_length=255)),
                (
                    "profile_picture",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("last_message", models.TextField(blank=True, null=True)),
                (
                    "last_contacted",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="fb_pages.facebookpage",
                    ),
                ),
            ],
        ),
    ]
